/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.basic.structure.dep.error;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return StringUtils.isBlank("  ");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
